# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BumpyPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, point_uuid: str=None, lat: float=None, lon: float=None, bump_score: float=None):  # noqa: E501
        """BumpyPoint - a model defined in Swagger

        :param point_uuid: The point_uuid of this BumpyPoint.  # noqa: E501
        :type point_uuid: str
        :param lat: The lat of this BumpyPoint.  # noqa: E501
        :type lat: float
        :param lon: The lon of this BumpyPoint.  # noqa: E501
        :type lon: float
        :param bump_score: The bump_score of this BumpyPoint.  # noqa: E501
        :type bump_score: float
        """
        self.swagger_types = {
            'point_uuid': str,
            'lat': float,
            'lon': float,
            'bump_score': float
        }

        self.attribute_map = {
            'point_uuid': 'pointUUID',
            'lat': 'lat',
            'lon': 'lon',
            'bump_score': 'bumpScore'
        }
        self._point_uuid = point_uuid
        self._lat = lat
        self._lon = lon
        self._bump_score = bump_score

    @classmethod
    def from_dict(cls, dikt) -> 'BumpyPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BumpyPoint of this BumpyPoint.  # noqa: E501
        :rtype: BumpyPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def point_uuid(self) -> str:
        """Gets the point_uuid of this BumpyPoint.


        :return: The point_uuid of this BumpyPoint.
        :rtype: str
        """
        return self._point_uuid

    @point_uuid.setter
    def point_uuid(self, point_uuid: str):
        """Sets the point_uuid of this BumpyPoint.


        :param point_uuid: The point_uuid of this BumpyPoint.
        :type point_uuid: str
        """

        self._point_uuid = point_uuid

    @property
    def lat(self) -> float:
        """Gets the lat of this BumpyPoint.


        :return: The lat of this BumpyPoint.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this BumpyPoint.


        :param lat: The lat of this BumpyPoint.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this BumpyPoint.


        :return: The lon of this BumpyPoint.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this BumpyPoint.


        :param lon: The lon of this BumpyPoint.
        :type lon: float
        """

        self._lon = lon

    @property
    def bump_score(self) -> float:
        """Gets the bump_score of this BumpyPoint.


        :return: The bump_score of this BumpyPoint.
        :rtype: float
        """
        return self._bump_score

    @bump_score.setter
    def bump_score(self, bump_score: float):
        """Sets the bump_score of this BumpyPoint.


        :param bump_score: The bump_score of this BumpyPoint.
        :type bump_score: float
        """

        self._bump_score = bump_score
