# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BumpyPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, lat: float=None, lon: float=None, bumpy_score: float=None):  # noqa: E501
        """BumpyPoint - a model defined in Swagger

        :param lat: The lat of this BumpyPoint.  # noqa: E501
        :type lat: float
        :param lon: The lon of this BumpyPoint.  # noqa: E501
        :type lon: float
        :param bumpy_score: The bumpy_score of this BumpyPoint.  # noqa: E501
        :type bumpy_score: float
        """
        self.swagger_types = {
            'lat': float,
            'lon': float,
            'bumpy_score': float
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon',
            'bumpy_score': 'bumpyScore'
        }
        self._lat = lat
        self._lon = lon
        self._bumpy_score = bumpy_score

    @classmethod
    def from_dict(cls, dikt) -> 'BumpyPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BumpyPoint of this BumpyPoint.  # noqa: E501
        :rtype: BumpyPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this BumpyPoint.


        :return: The lat of this BumpyPoint.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this BumpyPoint.


        :param lat: The lat of this BumpyPoint.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this BumpyPoint.


        :return: The lon of this BumpyPoint.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this BumpyPoint.


        :param lon: The lon of this BumpyPoint.
        :type lon: float
        """

        self._lon = lon

    @property
    def bumpy_score(self) -> float:
        """Gets the bumpy_score of this BumpyPoint.


        :return: The bumpy_score of this BumpyPoint.
        :rtype: float
        """
        return self._bumpy_score

    @bumpy_score.setter
    def bumpy_score(self, bumpy_score: float):
        """Sets the bumpy_score of this BumpyPoint.


        :param bumpy_score: The bumpy_score of this BumpyPoint.
        :type bumpy_score: float
        """

        self._bumpy_score = bumpy_score
