# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.processed_trip_elevation import ProcessedTripElevation  # noqa: F401,E501
from swagger_server.models.processed_trip_speed import ProcessedTripSpeed  # noqa: F401,E501
from swagger_server import util


class ProcessedTrip(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, device_uuid: str=None, trip_uuid: str=None, start_ts: datetime=None, end_ts: datetime=None, distance: float=None, speed: ProcessedTripSpeed=None, elevation: ProcessedTripElevation=None):  # noqa: E501
        """ProcessedTrip - a model defined in Swagger

        :param device_uuid: The device_uuid of this ProcessedTrip.  # noqa: E501
        :type device_uuid: str
        :param trip_uuid: The trip_uuid of this ProcessedTrip.  # noqa: E501
        :type trip_uuid: str
        :param start_ts: The start_ts of this ProcessedTrip.  # noqa: E501
        :type start_ts: datetime
        :param end_ts: The end_ts of this ProcessedTrip.  # noqa: E501
        :type end_ts: datetime
        :param distance: The distance of this ProcessedTrip.  # noqa: E501
        :type distance: float
        :param speed: The speed of this ProcessedTrip.  # noqa: E501
        :type speed: ProcessedTripSpeed
        :param elevation: The elevation of this ProcessedTrip.  # noqa: E501
        :type elevation: ProcessedTripElevation
        """
        self.swagger_types = {
            'device_uuid': str,
            'trip_uuid': str,
            'start_ts': datetime,
            'end_ts': datetime,
            'distance': float,
            'speed': ProcessedTripSpeed,
            'elevation': ProcessedTripElevation
        }

        self.attribute_map = {
            'device_uuid': 'deviceUUID',
            'trip_uuid': 'tripUUID',
            'start_ts': 'startTS',
            'end_ts': 'endTS',
            'distance': 'distance',
            'speed': 'speed',
            'elevation': 'elevation'
        }
        self._device_uuid = device_uuid
        self._trip_uuid = trip_uuid
        self._start_ts = start_ts
        self._end_ts = end_ts
        self._distance = distance
        self._speed = speed
        self._elevation = elevation

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessedTrip':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessedTrip of this ProcessedTrip.  # noqa: E501
        :rtype: ProcessedTrip
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_uuid(self) -> str:
        """Gets the device_uuid of this ProcessedTrip.


        :return: The device_uuid of this ProcessedTrip.
        :rtype: str
        """
        return self._device_uuid

    @device_uuid.setter
    def device_uuid(self, device_uuid: str):
        """Sets the device_uuid of this ProcessedTrip.


        :param device_uuid: The device_uuid of this ProcessedTrip.
        :type device_uuid: str
        """

        self._device_uuid = device_uuid

    @property
    def trip_uuid(self) -> str:
        """Gets the trip_uuid of this ProcessedTrip.


        :return: The trip_uuid of this ProcessedTrip.
        :rtype: str
        """
        return self._trip_uuid

    @trip_uuid.setter
    def trip_uuid(self, trip_uuid: str):
        """Sets the trip_uuid of this ProcessedTrip.


        :param trip_uuid: The trip_uuid of this ProcessedTrip.
        :type trip_uuid: str
        """

        self._trip_uuid = trip_uuid

    @property
    def start_ts(self) -> datetime:
        """Gets the start_ts of this ProcessedTrip.


        :return: The start_ts of this ProcessedTrip.
        :rtype: datetime
        """
        return self._start_ts

    @start_ts.setter
    def start_ts(self, start_ts: datetime):
        """Sets the start_ts of this ProcessedTrip.


        :param start_ts: The start_ts of this ProcessedTrip.
        :type start_ts: datetime
        """

        self._start_ts = start_ts

    @property
    def end_ts(self) -> datetime:
        """Gets the end_ts of this ProcessedTrip.


        :return: The end_ts of this ProcessedTrip.
        :rtype: datetime
        """
        return self._end_ts

    @end_ts.setter
    def end_ts(self, end_ts: datetime):
        """Sets the end_ts of this ProcessedTrip.


        :param end_ts: The end_ts of this ProcessedTrip.
        :type end_ts: datetime
        """

        self._end_ts = end_ts

    @property
    def distance(self) -> float:
        """Gets the distance of this ProcessedTrip.

        Expressed in meters  # noqa: E501

        :return: The distance of this ProcessedTrip.
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance: float):
        """Sets the distance of this ProcessedTrip.

        Expressed in meters  # noqa: E501

        :param distance: The distance of this ProcessedTrip.
        :type distance: float
        """

        self._distance = distance

    @property
    def speed(self) -> ProcessedTripSpeed:
        """Gets the speed of this ProcessedTrip.


        :return: The speed of this ProcessedTrip.
        :rtype: ProcessedTripSpeed
        """
        return self._speed

    @speed.setter
    def speed(self, speed: ProcessedTripSpeed):
        """Sets the speed of this ProcessedTrip.


        :param speed: The speed of this ProcessedTrip.
        :type speed: ProcessedTripSpeed
        """

        self._speed = speed

    @property
    def elevation(self) -> ProcessedTripElevation:
        """Gets the elevation of this ProcessedTrip.


        :return: The elevation of this ProcessedTrip.
        :rtype: ProcessedTripElevation
        """
        return self._elevation

    @elevation.setter
    def elevation(self, elevation: ProcessedTripElevation):
        """Sets the elevation of this ProcessedTrip.


        :param elevation: The elevation of this ProcessedTrip.
        :type elevation: ProcessedTripElevation
        """

        self._elevation = elevation
